#===-- lib/Expr/Makefile -----------------------------------*- Makefile -*--===#
#
#                     The KLEE Symbolic Virtual Machine
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
#===------------------------------------------------------------------------===#

LEVEL=../..

LIBRARYNAME=kleeData
DONT_BUILD_RELINKED=1
BUILD_ARCHIVE=1
BUILT_SOURCES = \
	CoverageLogs.pb.cc \
	Profiling.pb.cc \
	ConstraintSolving.pb.cc \
	Expr.pb.cc \
	DebugInfo.pb.cc \
	Statistics.pb.cc \
	States.pb.cc

include $(LEVEL)/Makefile.common
