#===-- lib/Solver/Makefile ---------------------------------*- Makefile -*--===#
#
#                     The KLEE Symbolic Virtual Machine
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
#===------------------------------------------------------------------------===#

LEVEL=../..

LIBRARYNAME=kleaverSolver
DONT_BUILD_RELINKED=1
BUILD_ARCHIVE=1
BUILT_SOURCES = \
	smt_service.pb.cc \
	smt_service.pb.h

include $(LEVEL)/Makefile.common
